version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18  # or your preferred Node.js version
  pre_build:
    commands:
      - echo Installing dependencies...
      - npm install
  post_build:
    commands:
      - echo Build completed on `date`

artifacts:
  files:
    - '**/*'
  name: myapp-$(date +%Y-%m-%d)
